@baseUrl = http://js-post-api.herokuapp.com/api

# Students

# @name getAllStudents
GET {{baseUrl}}/students?_page=1&_limit=10&_sort=mark&_order=desc

###

# @name getStudentById
GET {{baseUrl}}/students/b48a14d6-51b1-48f9-bde0-b2b369d53e9f

###

# @name addNewStudent
POST {{baseUrl}}/students
Content-Type: application/json

{
  "name": "Michale Test",
  "age": 27,
  "mark": 9,
  "gender": "male",
  "city": "pt"
}

###

# @name updateStudent
PATCH {{baseUrl}}/students/u6V7vww
Content-Type: application/json

{
  "name": "Michale Test"
}

###

# @name removeStudent
DELETE {{baseUrl}}/students/u6V7vww
